// Copyright The EyeDebugger Authors
// SPDX-License-Identifier: Apache-2.0

package container_test

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"testing"

	"github.com/eyedebugger/eyedebugger/internal/api"
	"github.com/eyedebugger/eyedebugger/internal/container"
)

// goldenOverride is the override for services "api" and "web" in a project
// directory @DIR@ (a JSON-escaped path): the bytes WriteOverride writes.
const goldenOverride = `# Generated by eyedbg compose launch; 'eyedbg compose restore' undoes it. Do not edit.
{
  "services": {
    "api": {
      "entrypoint": [
        "tail",
        "-f",
        "/dev/null"
      ],
      "command": [],
      "init": true,
      "volumes": [
        {
          "type": "bind",
          "source": "@SRC-api@",
          "target": "/app/api",
          "read_only": true,
          "bind": {
            "create_host_path": false
          }
        }
      ],
      "labels": {
        "dev.izzat.eyedbg.fast.dll": "Api.dll",
        "dev.izzat.eyedbg.fast.override": "@OVR@",
        "dev.izzat.eyedbg.fast.project": "Api.csproj",
        "dev.izzat.eyedbg.fast.version": "1",
        "dev.izzat.eyedbg.fast.workdir": "/app/api"
      }
    },
    "web": {
      "entrypoint": [
        "tail",
        "-f",
        "/dev/null"
      ],
      "command": [],
      "init": true,
      "volumes": [
        {
          "type": "bind",
          "source": "@SRC-web@",
          "target": "/app",
          "read_only": true,
          "bind": {
            "create_host_path": false
          }
        }
      ],
      "labels": {
        "dev.izzat.eyedbg.fast.dll": "Web.dll",
        "dev.izzat.eyedbg.fast.override": "@OVR@",
        "dev.izzat.eyedbg.fast.project": "Web/Web.csproj",
        "dev.izzat.eyedbg.fast.version": "1",
        "dev.izzat.eyedbg.fast.workdir": "/app"
      }
    }
  }
}
`

// jsonPath is p as it appears inside a JSON string.
func jsonPath(t *testing.T, p string) string {
	t.Helper()

	b, err := json.Marshal(p)
	if err != nil {
		t.Fatal(err)
	}

	return string(b[1 : len(b)-1])
}

// project makes <tmp>/<name>/services/<svc> for each service and returns the
// project directory and the override's path.
func project(t *testing.T, name string, svcs ...string) (dir, override string) {
	t.Helper()

	dir = filepath.Join(t.TempDir(), name)

	for _, s := range svcs {
		if err := os.MkdirAll(filepath.Join(dir, "services", s), 0o750); err != nil {
			t.Fatal(err)
		}
	}

	return dir, filepath.Join(dir, "override.yml")
}

func fastSvc(dir, name string) container.FastService {
	return container.FastService{
		Name: name, DLL: strings.ToUpper(name[:1]) + name[1:] + ".dll", WorkDir: "/app",
		Project: strings.ToUpper(name[:1]) + name[1:] + "/" + strings.ToUpper(name[:1]) + name[1:] + ".csproj",
		Source:  filepath.Join(dir, "services", name),
	}
}

func TestWriteOverrideGolden(t *testing.T) {
	t.Parallel()

	dir, ovr := project(t, "p", "api", "web")

	web := fastSvc(dir, "web")
	apiSvc := fastSvc(dir, "api")
	apiSvc.Project, apiSvc.WorkDir = "Api.csproj", "/app/api"

	// Given out of order: the file is sorted.
	if err := container.WriteOverride(ovr, []container.FastService{web, apiSvc}); err != nil {
		t.Fatal(err)
	}

	got, err := os.ReadFile(ovr)
	if err != nil {
		t.Fatal(err)
	}

	want := strings.NewReplacer(
		"@SRC-api@", jsonPath(t, filepath.Join(dir, "services", "api")),
		"@SRC-web@", jsonPath(t, filepath.Join(dir, "services", "web")),
		"@OVR@", jsonPath(t, ovr),
	).Replace(goldenOverride)

	if string(got) != want {
		t.Errorf("override differs:\n got %s\nwant %s", got, want)
	}

	if !strings.HasPrefix(string(got), container.OverrideHeader+"\n") {
		t.Error("the first line is not the header")
	}

	if runtime.GOOS != "windows" {
		if info, err := os.Stat(ovr); err != nil || info.Mode().Perm() != 0o600 {
			t.Errorf("mode = %v, %v", info.Mode(), err)
		}
	}
}

// TestWriteOverrideHoldsOnlyItsKeys parses the file and requires exactly the
// keys the contract allows: never environment, env_file, secrets, ports,
// healthcheck and the like.
func TestWriteOverrideHoldsOnlyItsKeys(t *testing.T) {
	t.Parallel()

	dir, ovr := project(t, "p", "web")

	if err := container.WriteOverride(ovr, []container.FastService{fastSvc(dir, "web")}); err != nil {
		t.Fatal(err)
	}

	doc := parseOverride(t, ovr)

	if keys := keysOf(doc); !slices.Equal(keys, []string{"services"}) {
		t.Errorf("top-level keys = %v", keys)
	}

	svc := asMap(t, asMap(t, doc["services"])["web"])

	if keys := keysOf(svc); !slices.Equal(keys, []string{"command", "entrypoint", "init", "labels", "volumes"}) {
		t.Errorf("service keys = %v: only entrypoint, command, init, volumes and labels may be there", keys)
	}

	mount := asMap(t, asSlice(t, svc["volumes"])[0])
	if keys := keysOf(mount); !slices.Equal(keys, []string{"bind", "read_only", "source", "target", "type"}) || mount["read_only"] != true {
		t.Errorf("mount = %v", mount)
	}

	for _, banned := range []string{"environment", "env_file", "secrets", "configs", "ports", "healthcheck", "user", "image", "build", "working_dir", "privileged", "cap_add"} {
		if _, has := svc[banned]; has {
			t.Errorf("the override sets %s", banned)
		}
	}

	raw, err := os.ReadFile(ovr)
	if err != nil {
		t.Fatal(err)
	}

	if strings.Contains(string(raw), "environment") {
		t.Error("the file mentions the environment")
	}
}

func parseOverride(t *testing.T, path string) map[string]any {
	t.Helper()

	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}

	first, body, ok := strings.Cut(string(raw), "\n")
	if !ok || first != container.OverrideHeader {
		t.Fatalf("first line = %q", first)
	}

	var doc map[string]any
	if err := json.Unmarshal([]byte(body), &doc); err != nil {
		t.Fatalf("the body after line 1 is not JSON: %v", err)
	}

	return doc
}

func asMap(t *testing.T, v any) map[string]any {
	t.Helper()

	m, ok := v.(map[string]any)
	if !ok {
		t.Fatalf("%v is not an object", v)
	}

	return m
}

func asSlice(t *testing.T, v any) []any {
	t.Helper()

	l, ok := v.([]any)
	if !ok || len(l) == 0 {
		t.Fatalf("%v is not a non-empty array", v)
	}

	return l
}

func asString(t *testing.T, v any) string {
	t.Helper()

	str, ok := v.(string)
	if !ok {
		t.Fatalf("%v is not a string", v)
	}

	return str
}

func keysOf(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}

	slices.Sort(keys)

	return keys
}

// TestWriteOverrideDoublesDollars: compose interpolates '$VAR' and '${VAR}'
// in every string of its files; a '$' must go out as '$$', and no lone '$'
// may remain anywhere in a value.
func TestWriteOverrideDoublesDollars(t *testing.T) {
	t.Parallel()

	if runtime.GOOS == "windows" {
		t.Skip("'$' is fine in a Windows path, but this test builds Unix-style names")
	}

	for _, name := range []string{"a$b", "a$$b", "a${X}b", "$HOME", "x$", "${X:-y}$(z)"} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			dir, ovr := project(t, name, "web")
			svc := fastSvc(dir, "web")
			svc.Project = "My$Dir/${X}/Web.csproj"

			if err := container.WriteOverride(ovr, []container.FastService{svc}); err != nil {
				t.Fatal(err)
			}

			doc := parseOverride(t, ovr)
			web := asMap(t, asMap(t, doc["services"])["web"])
			mount := asMap(t, asSlice(t, web["volumes"])[0])
			labels := asMap(t, web["labels"])

			values := map[string]string{
				"source":         asString(t, mount["source"]),
				"label override": asString(t, labels["dev.izzat.eyedbg.fast.override"]),
				"label project":  asString(t, labels["dev.izzat.eyedbg.fast.project"]),
			}

			wants := map[string]string{"source": svc.Source, "label override": ovr, "label project": svc.Project}

			for k, v := range values {
				// Compose's reading of the value: '$$' is one '$'.
				if got := strings.ReplaceAll(v, "$$", "$"); got != wants[k] {
					t.Errorf("%s: compose would read %q, want %q (file has %q)", k, got, wants[k], v)
				}

				// Every '$' is half of a pair: nothing is left to interpolate.
				if strings.Contains(strings.ReplaceAll(v, "$$", ""), "$") {
					t.Errorf("%s: a lone '$' in %q", k, v)
				}
			}
		})
	}
}

func TestWriteOverrideRefusals(t *testing.T) {
	t.Parallel()

	// Each case varies one value of an otherwise valid layout (services web
	// and api under a project directory d, the override at o).
	type build func(d, o string) (path string, svcs []container.FastService)

	one := func(mod func(s *container.FastService)) build {
		return func(d, o string) (string, []container.FastService) {
			s := fastSvc(d, "web")
			mod(&s)

			return o, []container.FastService{s}
		}
	}

	atPath := func(rel string) build {
		return func(d, _ string) (string, []container.FastService) {
			return strings.Replace(rel, "@D@", d, 1), []container.FastService{fastSvc(d, "web")}
		}
	}

	sep := string(filepath.Separator)

	tests := []struct {
		name  string
		build build
	}{
		{"no services", func(_, o string) (string, []container.FastService) { return o, []container.FastService{} }},
		{"relative path", atPath("override.yml")},
		{"wrong file name", atPath("@D@" + sep + "other.yml")},
		{"unclean path", atPath("@D@" + sep + "." + sep + "override.yml")},
		{"control char in path", atPath("@D@" + sep + "x\n" + sep + "override.yml")},
		{"bad service name", one(func(s *container.FastService) { s.Name = "../x" })},
		{"service name with a space", one(func(s *container.FastService) { s.Name = "we b" })},
		{"dll with a slash", one(func(s *container.FastService) { s.DLL = "a/Web.dll" })},
		{"dll with ./", one(func(s *container.FastService) { s.DLL = "./Web.dll" })},
		{"system workdir", one(func(s *container.FastService) { s.WorkDir = "/usr/app" })},
		{"eyedbg's own workdir", one(func(s *container.FastService) { s.WorkDir = "/.eyedbg-netcoredbg-3.2.0-1092" })},
		{"relative workdir", one(func(s *container.FastService) { s.WorkDir = "app" })},
		{"project dotdot", one(func(s *container.FastService) { s.Project = "../Web.csproj" })},
		{"project absolute", one(func(s *container.FastService) { s.Project = "/Web.csproj" })},
		{"project with a newline", one(func(s *container.FastService) { s.Project = "a\nb.csproj" })},
		{"source elsewhere", one(func(s *container.FastService) { s.Source = filepath.Dir(s.Source) })},
		{"source is the root", one(func(s *container.FastService) { s.Source = sep })},
		{"source is the home directory", one(func(s *container.FastService) { s.Source, _ = os.UserHomeDir() })},
		{"source of another service", one(func(s *container.FastService) { s.Source = filepath.Join(filepath.Dir(s.Source), "api") })},
		{"source with dotdot", one(func(s *container.FastService) {
			s.Source = filepath.Join(s.Source, "..", "..", "services", "web") + sep + "."
		})},
		{"source missing", one(func(s *container.FastService) {
			s.Name, s.Source = "gone", filepath.Join(filepath.Dir(s.Source), "gone")
			s.DLL, s.Project = "Gone.dll", "Gone.csproj"
		})},
		{"duplicate service", func(d, o string) (string, []container.FastService) {
			return o, []container.FastService{fastSvc(d, "web"), fastSvc(d, "web")}
		}},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			d, o := project(t, "p", "web", "api")
			path, svcs := tt.build(d, o)

			err := container.WriteOverride(path, svcs)
			if api.CodeOf(err) != api.CodeInvalidRequest {
				t.Fatalf("err = %v (%s), want INVALID_REQUEST", err, api.CodeOf(err))
			}

			assertNoStrayFiles(t, d)
		})
	}

	// The layout the refusals vary is itself valid.
	d, o := project(t, "p", "web", "api")
	if err := container.WriteOverride(o, []container.FastService{fastSvc(d, "web")}); err != nil {
		t.Fatalf("the base layout: %v", err)
	}
}

// assertNoStrayFiles requires that nothing but the services directory is in
// dir: no override, no temporary file.
func assertNoStrayFiles(t *testing.T, dir string) {
	t.Helper()

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}

	for _, e := range entries {
		if e.Name() != "services" {
			t.Errorf("stray %s in %s", e.Name(), dir)
		}
	}
}

func TestWriteOverrideTooManyServices(t *testing.T) {
	t.Parallel()

	dir, ovr := project(t, "p")

	svcs := make([]container.FastService, 65)
	for i := range svcs {
		name := fmt.Sprintf("s%d", i)
		if err := os.MkdirAll(filepath.Join(dir, "services", name), 0o750); err != nil {
			t.Fatal(err)
		}

		svcs[i] = fastSvc(dir, name)
	}

	if err := container.WriteOverride(ovr, svcs); api.CodeOf(err) != api.CodeInvalidRequest {
		t.Errorf("err = %v", err)
	}

	if err := container.WriteOverride(ovr, svcs[:64]); err != nil {
		t.Errorf("64 services: %v", err)
	}
}

func TestWriteOverrideRefusesSymlinkedSource(t *testing.T) {
	t.Parallel()

	dir, ovr := project(t, "p", "real")
	svc := fastSvc(dir, "web")

	// services/web is a symlink to a directory elsewhere: it would let the
	// override mount any directory.
	if err := os.Symlink(filepath.Join(dir, "services", "real"), svc.Source); err != nil {
		t.Skipf("symlinks: %v", err)
	}

	if err := container.WriteOverride(ovr, []container.FastService{svc}); api.CodeOf(err) != api.CodeInvalidRequest {
		t.Errorf("err = %v", err)
	}

	if _, err := os.Lstat(ovr); err == nil {
		t.Error("an override was written")
	}
}

// TestWriteOverrideRefusesAliasedSources: two names that reach one directory
// (a case-insensitive file system) would run each other's build.
func TestWriteOverrideRefusesAliasedSources(t *testing.T) {
	t.Parallel()

	dir, ovr := project(t, "p", "Web")

	if _, err := os.Lstat(filepath.Join(dir, "services", "web")); err != nil {
		t.Skip("a case-sensitive file system: 'Web' and 'web' are different directories")
	}

	err := container.WriteOverride(ovr, []container.FastService{fastSvc(dir, "Web"), fastSvc(dir, "web")})
	if api.CodeOf(err) != api.CodeInvalidRequest || !strings.Contains(err.Error(), "same build directory") {
		t.Errorf("err = %v", err)
	}
}

func TestWriteOverrideReplacesAndLeavesNoTemp(t *testing.T) {
	t.Parallel()

	dir, ovr := project(t, "p", "web")
	svc := fastSvc(dir, "web")

	if err := os.WriteFile(ovr, []byte("old"), 0o600); err != nil {
		t.Fatal(err)
	}

	if err := container.WriteOverride(ovr, []container.FastService{svc}); err != nil {
		t.Fatal(err)
	}

	if raw, _ := os.ReadFile(ovr); !strings.HasPrefix(string(raw), container.OverrideHeader) {
		t.Errorf("not replaced: %q", raw)
	}

	if runtime.GOOS != "windows" {
		if info, _ := os.Stat(ovr); info.Mode().Perm() != 0o600 {
			t.Errorf("a replaced file's mode = %v", info.Mode().Perm())
		}
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}

	for _, e := range entries {
		if e.Name() != "services" && e.Name() != "override.yml" {
			t.Errorf("temporary file left: %s", e.Name())
		}
	}
}

// TestWriteOverrideFailureLeavesNoTemp: the rename fails (a non-empty
// directory is at the path), and the temporary file goes.
func TestWriteOverrideFailureLeavesNoTemp(t *testing.T) {
	t.Parallel()

	dir, ovr := project(t, "p", "web")

	if err := os.MkdirAll(filepath.Join(ovr, "inner"), 0o750); err != nil {
		t.Fatal(err)
	}

	if err := container.WriteOverride(ovr, []container.FastService{fastSvc(dir, "web")}); err == nil {
		t.Fatal("replacing a directory worked")
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}

	for _, e := range entries {
		if e.Name() != "services" && e.Name() != "override.yml" {
			t.Errorf("temporary file left: %s", e.Name())
		}
	}

	// And the directory is untouched.
	if _, err := os.Stat(filepath.Join(ovr, "inner")); err != nil {
		t.Errorf("the directory at the path was disturbed: %v", err)
	}
}

func TestWriteOverrideMissingParent(t *testing.T) {
	t.Parallel()

	dir := filepath.Join(t.TempDir(), "nope")
	svc := container.FastService{Name: "web", DLL: "Web.dll", WorkDir: "/app", Project: "Web.csproj", Source: filepath.Join(dir, "services", "web")}

	if err := container.WriteOverride(filepath.Join(dir, "override.yml"), []container.FastService{svc}); err == nil {
		t.Error("written into a directory that doesn't exist")
	}
}

// recordedOverride writes an override recording svcs (service -> labels) at
// path, with the header eyedbg writes.
func recordedOverride(t *testing.T, path string, svcs map[string]map[string]string) {
	t.Helper()

	type svc struct {
		Labels map[string]string `json:"labels"`
	}

	doc := struct {
		Services map[string]svc `json:"services"`
	}{map[string]svc{}}

	for n, l := range svcs {
		doc.Services[n] = svc{Labels: l}
	}

	body, err := json.Marshal(doc)
	if err != nil {
		t.Fatal(err)
	}

	if err := os.WriteFile(path, append([]byte(container.OverrideHeader+"\n"), body...), 0o600); err != nil {
		t.Fatal(err)
	}
}

// TestRecordedCorroboratesLabels: a container's fast-mode labels count only
// when eyedbg's override records the same ones for that service, at that
// path. Every field is checked: a label an image can copy onto any
// container proves nothing.
func TestRecordedCorroboratesLabels(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	path := filepath.Join(dir, container.OverrideName)

	recorded := func(over, dll, wd, project string) map[string]string {
		return map[string]string{
			"dev.izzat.eyedbg.fast.version": "1", "dev.izzat.eyedbg.fast.override": over,
			"dev.izzat.eyedbg.fast.dll": dll, "dev.izzat.eyedbg.fast.workdir": wd, "dev.izzat.eyedbg.fast.project": project,
		}
	}

	recordedOverride(t, path, map[string]map[string]string{
		"web":  recorded(path, "Web.dll", "/app", "Web/Web.csproj"),
		"cash": recorded(path, "Co.dll", "/app", "Co$$t/Co.csproj"), // '$' is doubled in a file
	})

	rec, err := container.ReadRecorded(path)
	if err != nil {
		t.Fatal(err)
	}

	same := func() *container.FastLabels {
		return &container.FastLabels{Version: "1", Override: path, DLL: "Web.dll", WorkDir: "/app", ProjectLabel: "Web/Web.csproj"}
	}

	tests := []struct {
		name    string
		service string
		edit    func(l *container.FastLabels)
		want    bool
	}{
		{"the recorded labels", "web", func(*container.FastLabels) {}, true},
		{"a dollar sign, doubled in the file", "cash", func(l *container.FastLabels) {
			l.DLL, l.ProjectLabel = "Co.dll", "Co$t/Co.csproj"
		}, true},
		{"a service the override doesn't record", "api", func(*container.FastLabels) {}, false},
		{"another override path", "web", func(l *container.FastLabels) { l.Override = filepath.Join(dir, "elsewhere", container.OverrideName) }, false},
		{"another assembly", "web", func(l *container.FastLabels) { l.DLL = "Evil.dll" }, false},
		{"another working directory", "web", func(l *container.FastLabels) { l.WorkDir = "/src" }, false},
		{"another project", "web", func(l *container.FastLabels) { l.ProjectLabel = "data/x/Evil.csproj" }, false},
		{"no project label", "web", func(l *container.FastLabels) { l.ProjectLabel = "" }, false},
		{"another version, as recorded in the file", "web", func(l *container.FastLabels) { l.Version = "2" }, false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			l := same()
			tt.edit(l)

			if got := rec.Corroborates(tt.service, l); got != tt.want {
				t.Errorf("Corroborates(%s, %+v) = %v, want %v", tt.service, l, got, tt.want)
			}
		})
	}

	if rec.Corroborates("web", nil) {
		t.Error("nil labels corroborated")
	}

	// A copy of the file elsewhere is not the file the container was made with.
	copied := filepath.Join(dir, "copy", container.OverrideName)
	if err := os.MkdirAll(filepath.Dir(copied), 0o700); err != nil {
		t.Fatal(err)
	}

	recordedOverride(t, copied, map[string]map[string]string{"web": recorded(path, "Web.dll", "/app", "Web/Web.csproj")})

	other, err := container.ReadRecorded(copied)
	if err != nil {
		t.Fatal(err)
	}

	if other.Corroborates("web", same()) {
		t.Error("a file at another path than the labels name corroborated them")
	}
}

// TestRecordedOfOtherVersion: a label format this code doesn't read is
// corroborated by its version and override alone, so the caller can say
// "another eyedbg's" about a container eyedbg's own file records.
func TestRecordedOfOtherVersion(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), container.OverrideName)
	recordedOverride(t, path, map[string]map[string]string{"web": {"dev.izzat.eyedbg.fast.version": "2", "dev.izzat.eyedbg.fast.override": path}})

	rec, err := container.ReadRecorded(path)
	if err != nil {
		t.Fatal(err)
	}

	if !rec.Corroborates("web", &container.FastLabels{Version: "2", Override: path}) {
		t.Error("version 2 as recorded was not corroborated")
	}

	if rec.Corroborates("web", &container.FastLabels{Version: "3", Override: path}) {
		t.Error("another version was corroborated")
	}
}

// TestReadRecordedRefusesWhatIsNotEyedbgs: a file that is missing records
// nothing without an error; anything but the regular, header-first, JSON file
// eyedbg writes is an error and records nothing.
func TestReadRecordedRefusesWhatIsNotEyedbgs(t *testing.T) {
	t.Parallel()

	labels := map[string]map[string]string{"web": {"dev.izzat.eyedbg.fast.version": "1"}}

	tests := []struct {
		name    string
		prepare func(t *testing.T, path string)
		wantErr bool
	}{
		{"missing", func(*testing.T, string) {}, false},
		{"not eyedbg's header", func(t *testing.T, p string) {
			t.Helper()

			if err := os.WriteFile(p, []byte("# something else\n{\"services\":{}}"), 0o600); err != nil {
				t.Fatal(err)
			}
		}, true},
		{"not JSON", func(t *testing.T, p string) {
			t.Helper()

			if err := os.WriteFile(p, []byte(container.OverrideHeader+"\nservices: {}\n"), 0o600); err != nil {
				t.Fatal(err)
			}
		}, true},
		{"a directory", func(t *testing.T, p string) {
			t.Helper()

			if err := os.Mkdir(p, 0o700); err != nil {
				t.Fatal(err)
			}
		}, true},
		{"a symlink to a good file", func(t *testing.T, p string) {
			t.Helper()

			target := p + ".target"
			recordedOverride(t, target, labels)

			if err := os.Symlink(target, p); err != nil {
				t.Skip("no symlinks here:", err)
			}
		}, true},
		{"too big", func(t *testing.T, p string) {
			t.Helper()

			if err := os.WriteFile(p, append([]byte(container.OverrideHeader+"\n"), bytes.Repeat([]byte(" "), 2<<20)...), 0o600); err != nil {
				t.Fatal(err)
			}
		}, true},
		{"good", func(t *testing.T, p string) {
			t.Helper()

			recordedOverride(t, p, labels)
		}, false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			path := filepath.Join(t.TempDir(), container.OverrideName)
			tt.prepare(t, path)

			rec, err := container.ReadRecorded(path)
			if (err != nil) != tt.wantErr {
				t.Fatalf("err = %v, want error: %v", err, tt.wantErr)
			}

			if tt.wantErr && rec.Corroborates("web", &container.FastLabels{Version: "1", Override: path}) {
				t.Error("a refused file corroborated labels")
			}
		})
	}
}
