// Copyright The EyeDebugger Authors
// SPDX-License-Identifier: Apache-2.0

package container

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/eyedebugger/eyedebugger/internal/api"
)

// OverrideHeader is the first line of an override file eyedbg writes
// (docs/adr/0021, D15); a file that doesn't start with it isn't eyedbg's.
const OverrideHeader = "# Generated by eyedbg compose launch; 'eyedbg compose restore' undoes it. Do not edit."

// OverrideName is the override's file name inside a project's directory.
const OverrideName = "override.yml"

// maxOverrideServices bounds the services of one override (the same bound as
// a group).
const maxOverrideServices = 64

// FastService is one service of the override: what its container idles on
// and what a later launch needs to know, as labels.
type FastService struct {
	// Name is the compose service, DLL the assembly its entrypoint named,
	// WorkDir the container's working directory (the mount target) and
	// Project the project file's path below the compose directory.
	Name, DLL, WorkDir, Project string
	// Source is the host directory with the build, mounted read-only at
	// WorkDir: it must be <override's directory>/services/<Name>, a real
	// directory.
	Source string
}

// overrideDoc is the override file's JSON. Its keys are compose's.
type overrideDoc struct {
	Services map[string]overrideService `json:"services"`
}

type overrideService struct {
	Entrypoint []string          `json:"entrypoint"`
	Command    []string          `json:"command"`
	Init       bool              `json:"init"`
	Volumes    []overrideMount   `json:"volumes"`
	Labels     map[string]string `json:"labels"`
}

type overrideMount struct {
	Type     string       `json:"type"`
	Source   string       `json:"source"`
	Target   string       `json:"target"`
	ReadOnly bool         `json:"read_only"` //nolint:tagliatelle // Compose's own key.
	Bind     overrideBind `json:"bind"`
}

type overrideBind struct {
	CreateHostPath bool `json:"create_host_path"` //nolint:tagliatelle // Compose's own key.
}

// WriteOverride writes the override file at path (docs/adr/0021, D15):
// OverrideHeader, then JSON with, for each service of svcs sorted by name,
// only
//
//	entrypoint ["tail", "-f", "/dev/null"], command [], init true,
//	volumes [{type bind, source, target, read_only true,
//	          bind {create_host_path false}}],
//	labels {dev.izzat.eyedbg.fast.{version, override, dll, workdir, project}}
//
// and never environment, env_file, secrets, configs, healthcheck, ports,
// user, image, build or working_dir. Every string has '$' doubled (compose
// interpolates it). path must be an absolute <dir>/override.yml; each
// Source <dir>/services/<Name>, so the override can't mount any other host
// directory. The file is written to a temporary file in dir (0600) and
// renamed over path; a failure leaves no temporary file.
func WriteOverride(path string, svcs []FastService) error {
	if !plainAbsPath(path) || filepath.Base(path) != OverrideName || filepath.Clean(path) != path {
		return api.NewError(api.CodeInvalidRequest, "the override path is not a clean absolute path ending in "+OverrideName+": "+show(path, 80), "")
	}

	doc, err := overrideFor(path, svcs)
	if err != nil {
		return err
	}

	var buf bytes.Buffer

	buf.WriteString(OverrideHeader + "\n")

	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")

	if err := enc.Encode(doc); err != nil {
		return fmt.Errorf("encode override: %w", err)
	}

	return writeAtomic(path, buf.Bytes())
}

// overrideFor checks svcs and builds the file's document.
func overrideFor(path string, svcs []FastService) (overrideDoc, error) {
	if len(svcs) == 0 || len(svcs) > maxOverrideServices {
		return overrideDoc{}, api.NewError(api.CodeInvalidRequest, fmt.Sprintf("an override holds 1 to %d services", maxOverrideServices), "")
	}

	dir := filepath.Dir(path)
	doc := overrideDoc{Services: make(map[string]overrideService, len(svcs))}

	var seen []os.FileInfo

	for _, s := range sortedServices(svcs) {
		if _, dup := doc.Services[s.Name]; dup {
			return overrideDoc{}, api.NewError(api.CodeInvalidRequest, "service "+show(s.Name, 40)+" is twice in the override", "")
		}

		info, err := checkFastService(dir, s)
		if err != nil {
			return overrideDoc{}, err
		}

		// Two names that reach one directory (a case-insensitive file system,
		// a symlink) would run each other's build.
		if slices.ContainsFunc(seen, func(o os.FileInfo) bool { return os.SameFile(o, info) }) {
			return overrideDoc{}, api.NewError(api.CodeInvalidRequest,
				"service "+show(s.Name, 40)+" has the same build directory as another service (names that differ only in case?)", "")
		}

		seen = append(seen, info)
		doc.Services[s.Name] = fastOverrideService(path, s)
	}

	return doc, nil
}

func sortedServices(svcs []FastService) []FastService {
	return slices.SortedFunc(slices.Values(svcs), func(a, b FastService) int { return strings.Compare(a.Name, b.Name) })
}

// checkFastService checks every value of s that reaches the file, and
// returns its source directory's info.
func checkFastService(dir string, s FastService) (os.FileInfo, error) {
	if err := ValidateService(s.Name); err != nil {
		return nil, err
	}

	if !ValidDLL(s.DLL) {
		return nil, api.NewError(api.CodeInvalidRequest, "service "+s.Name+": the assembly name is not valid: "+show(s.DLL, 60), "")
	}

	if err := ValidAppDir(s.WorkDir); err != nil {
		return nil, err
	}

	if !ValidProjectRel(s.Project) {
		return nil, api.NewError(api.CodeInvalidRequest, "service "+s.Name+": the project path is not valid: "+show(s.Project, 80), "")
	}

	if want := filepath.Join(dir, "services", s.Name); s.Source != want || !plainAbsPath(s.Source) {
		return nil, api.NewError(api.CodeInvalidRequest, "service "+s.Name+": the build directory must be "+show(want, 120)+", not "+show(s.Source, 120), "")
	}

	info, err := os.Lstat(s.Source)
	if err != nil || !info.IsDir() {
		return nil, api.NewError(api.CodeInvalidRequest, "service "+s.Name+": the build directory "+show(s.Source, 120)+" is not an existing directory", "")
	}

	return info, nil
}

// fastOverrideService is the service's fragment, '$' doubled in every
// string.
func fastOverrideService(path string, s FastService) overrideService {
	return overrideService{
		Entrypoint: []string{"tail", "-f", "/dev/null"},
		Command:    []string{},
		Init:       true,
		Volumes: []overrideMount{{
			Type: "bind", Source: composeEscape(s.Source), Target: composeEscape(s.WorkDir), ReadOnly: true,
			Bind: overrideBind{CreateHostPath: false},
		}},
		Labels: map[string]string{
			labelFastVersion: FastVersion,
			labelFastMode:    composeEscape(path),
			labelFastDLL:     composeEscape(s.DLL),
			labelFastWorkDir: composeEscape(s.WorkDir),
			labelFastProject: composeEscape(s.Project),
		},
	}
}

// composeEscape is s with '$' doubled: compose interpolates '$VAR' and
// '${VAR}' in every string of its files, and reads '$$' as one '$'.
func composeEscape(s string) string { return strings.ReplaceAll(s, "$", "$$") }

// tempTries bounds picking a fresh temporary name.
const tempTries = 5

// writeAtomic writes data to path through a temporary file next to it
// (0600, fresh name, synced) and a rename; any failure removes the
// temporary file.
func writeAtomic(path string, data []byte) (err error) {
	f, tmp, err := createTemp(filepath.Dir(path), filepath.Base(path)+".tmp-")
	if err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}

	defer func() {
		if err != nil {
			_ = os.Remove(tmp)
		}
	}()

	_, werr := f.Write(data)
	if werr == nil {
		werr = f.Sync()
	}

	if cerr := f.Close(); werr == nil {
		werr = cerr
	}

	if werr != nil {
		return fmt.Errorf("write %s: %w", path, werr)
	}

	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("replace %s: %w", path, err)
	}

	return nil
}

// createTemp creates a fresh file dir/<prefix><16 hex> (0600) that didn't
// exist.
func createTemp(dir, prefix string) (*os.File, string, error) {
	for range tempTries {
		var b [8]byte
		if _, err := rand.Read(b[:]); err != nil {
			return nil, "", fmt.Errorf("pick a file name: %w", err)
		}

		name := filepath.Join(dir, prefix+hex.EncodeToString(b[:]))

		f, err := os.OpenFile(name, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
		if errors.Is(err, fs.ErrExist) {
			continue
		}

		if err != nil {
			return nil, "", fmt.Errorf("create a temporary file in %s: %w", dir, err)
		}

		return f, name, nil
	}

	return nil, "", fmt.Errorf("create a temporary file in %s: %d names taken", dir, tempTries)
}
